name: pizza_repository
description: The repo that handles the pizzas.
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  firebase_auth: ^0.18.4+1
#  cloud_firestore: ^0.14.4
#  firebase_core: ^0.5.3
#  firebase_storage: ^3.1.6
#  google_sign_in: ^4.5.1
#  shared_preferences: ^0.5.12+4
#  provider: ^4.3.2+2
#  equatable: ^1.2.5
#  dartz: ^0.9.2
#  injectable: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true